logging.level.smarthome= info
logging.level.smarthome.*= info
logging.level.smarthome.runners= debug
logging.level.smarthome.system= info
logging.level.smarthome.i2c= info

logging.level.newsmarthome.*= info
logging.level.newsmarthome.i2c.I2CHardware= info
logging.level.newsmarthome.i2c.MasterToSlaveConverter = info
logging.level.newsmarthome.controller=debug
logging.level.newsmarthome.runners= info
logging.level.newsmarthome.automation= debug

logging.file.name = smarthome/log.log
logging.logback.rollingpolicy.max-file-size= 1GB

spring.task.scheduling.pool.size=5

# I2C - odpytywanie eventow z przyciskow (niestandardowe klikniecia)
# co ile ms odpytywac slave-y o eventy
i2c.event.poll-interval-ms=5
# ile ms czekac pomiedzy wyslaniem 'W'/'G' a odczytem odpowiedzi (zwiekszyc, jesli pojawiaja sie bledne odczyty)
i2c.event.response-delay-ms=1

server.port=8080